# Build
FROM golang:alpine3.15 as builder

RUN mkdir -p /home/builder
WORKDIR /home/builder

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
ARG BUILD
ARG VERSION
ARG SERVICE_NAME

RUN go build -ldflags "-w -s -X main.BuildVersion=${VERSION} -X main.BuildHash=${BUILD} -X main.ServiceName=${SERVICE_NAME}" -o ./bin/service -v ./cmd/service.go
RUN cp ./bin/service

# Runner
FROM scratch
COPY --from=builder /home/builder/bin/service /bin/service
EXPOSE 80 3000
HEALTHCHECK --interval=5s --timeout=3s --retries=3 CMD ["/bin/service", "health"]
CMD ["/bin/service", "start"]

